@API = http://localhost:4000

### GET PROVINCES
GET {{API}}/provinces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAyMzA1MTYwLCJleHAiOjE3MDQ4OTcxNjB9.1wi02n45_iDzMIoKobaBIxKyAM-ghdNzBo3N-G-g5Is

### CREATE PROVINCE
POST {{API}}/provinces
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAyMzA1MTYwLCJleHAiOjE3MDQ4OTcxNjB9.1wi02n45_iDzMIoKobaBIxKyAM-ghdNzBo3N-G-g5Is

{
    "province": "Tucumán"
}

### REMOVE PROVINCE
DELETE {{API}}/provinces/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzAyMzA1MTYwLCJleHAiOjE3MDQ4OTcxNjB9.1wi02n45_iDzMIoKobaBIxKyAM-ghdNzBo3N-G-g5Is