import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'

import Header from '@/components/header/header'

const lato = Lato({ subsets: ['latin'], weight: '400' })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="shortcut icon" href="oven.svg" type="image/x-icon" />
      </head>
      <body className={lato.className}>
        <div className="container-body">
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
